name = "lapce-powershell"
display-name = "lapce-powershell"
description = "PowerShell language support for Lapce provided by PowerShell Editor Services"
version = "0.0.1"
author = "instanceid"
repository = "instance-id/lapce-powershell-plugin"
wasm = "lapce-powershell.wasm"

[configuration]
language_id = "powershell"
#[configuration.options.diagnostics]
#enable = false
#enableExperimental = false
